/**
 * @fileoverview gRPC-Web generated client stub for job_application_service
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.27.3
// source: job_application.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as job_application_pb from './job_application_pb'; // proto import: "job_application.proto"


export class JobApplicationServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreateJobApplication = new grpcWeb.MethodDescriptor(
    '/job_application_service.JobApplicationService/CreateJobApplication',
    grpcWeb.MethodType.UNARY,
    job_application_pb.CreateJobApplicationRequest,
    job_application_pb.CreateJobApplicationResponse,
    (request: job_application_pb.CreateJobApplicationRequest) => {
      return request.serializeBinary();
    },
    job_application_pb.CreateJobApplicationResponse.deserializeBinary
  );

  createJobApplication(
    request: job_application_pb.CreateJobApplicationRequest,
    metadata?: grpcWeb.Metadata | null): Promise<job_application_pb.CreateJobApplicationResponse>;

  createJobApplication(
    request: job_application_pb.CreateJobApplicationRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: job_application_pb.CreateJobApplicationResponse) => void): grpcWeb.ClientReadableStream<job_application_pb.CreateJobApplicationResponse>;

  createJobApplication(
    request: job_application_pb.CreateJobApplicationRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: job_application_pb.CreateJobApplicationResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/job_application_service.JobApplicationService/CreateJobApplication',
        request,
        metadata || {},
        this.methodDescriptorCreateJobApplication,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/job_application_service.JobApplicationService/CreateJobApplication',
    request,
    metadata || {},
    this.methodDescriptorCreateJobApplication);
  }

  methodDescriptorReadJobApplication = new grpcWeb.MethodDescriptor(
    '/job_application_service.JobApplicationService/ReadJobApplication',
    grpcWeb.MethodType.UNARY,
    job_application_pb.ReadJobApplicationRequest,
    job_application_pb.ReadJobApplicationResponse,
    (request: job_application_pb.ReadJobApplicationRequest) => {
      return request.serializeBinary();
    },
    job_application_pb.ReadJobApplicationResponse.deserializeBinary
  );

  readJobApplication(
    request: job_application_pb.ReadJobApplicationRequest,
    metadata?: grpcWeb.Metadata | null): Promise<job_application_pb.ReadJobApplicationResponse>;

  readJobApplication(
    request: job_application_pb.ReadJobApplicationRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: job_application_pb.ReadJobApplicationResponse) => void): grpcWeb.ClientReadableStream<job_application_pb.ReadJobApplicationResponse>;

  readJobApplication(
    request: job_application_pb.ReadJobApplicationRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: job_application_pb.ReadJobApplicationResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/job_application_service.JobApplicationService/ReadJobApplication',
        request,
        metadata || {},
        this.methodDescriptorReadJobApplication,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/job_application_service.JobApplicationService/ReadJobApplication',
    request,
    metadata || {},
    this.methodDescriptorReadJobApplication);
  }

  methodDescriptorUpdateJobApplication = new grpcWeb.MethodDescriptor(
    '/job_application_service.JobApplicationService/UpdateJobApplication',
    grpcWeb.MethodType.UNARY,
    job_application_pb.UpdateJobApplicationRequest,
    job_application_pb.UpdateJobApplicationResponse,
    (request: job_application_pb.UpdateJobApplicationRequest) => {
      return request.serializeBinary();
    },
    job_application_pb.UpdateJobApplicationResponse.deserializeBinary
  );

  updateJobApplication(
    request: job_application_pb.UpdateJobApplicationRequest,
    metadata?: grpcWeb.Metadata | null): Promise<job_application_pb.UpdateJobApplicationResponse>;

  updateJobApplication(
    request: job_application_pb.UpdateJobApplicationRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: job_application_pb.UpdateJobApplicationResponse) => void): grpcWeb.ClientReadableStream<job_application_pb.UpdateJobApplicationResponse>;

  updateJobApplication(
    request: job_application_pb.UpdateJobApplicationRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: job_application_pb.UpdateJobApplicationResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/job_application_service.JobApplicationService/UpdateJobApplication',
        request,
        metadata || {},
        this.methodDescriptorUpdateJobApplication,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/job_application_service.JobApplicationService/UpdateJobApplication',
    request,
    metadata || {},
    this.methodDescriptorUpdateJobApplication);
  }

  methodDescriptorDeleteJobApplication = new grpcWeb.MethodDescriptor(
    '/job_application_service.JobApplicationService/DeleteJobApplication',
    grpcWeb.MethodType.UNARY,
    job_application_pb.DeleteJobApplicationRequest,
    job_application_pb.DeleteJobApplicationResponse,
    (request: job_application_pb.DeleteJobApplicationRequest) => {
      return request.serializeBinary();
    },
    job_application_pb.DeleteJobApplicationResponse.deserializeBinary
  );

  deleteJobApplication(
    request: job_application_pb.DeleteJobApplicationRequest,
    metadata?: grpcWeb.Metadata | null): Promise<job_application_pb.DeleteJobApplicationResponse>;

  deleteJobApplication(
    request: job_application_pb.DeleteJobApplicationRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: job_application_pb.DeleteJobApplicationResponse) => void): grpcWeb.ClientReadableStream<job_application_pb.DeleteJobApplicationResponse>;

  deleteJobApplication(
    request: job_application_pb.DeleteJobApplicationRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: job_application_pb.DeleteJobApplicationResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/job_application_service.JobApplicationService/DeleteJobApplication',
        request,
        metadata || {},
        this.methodDescriptorDeleteJobApplication,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/job_application_service.JobApplicationService/DeleteJobApplication',
    request,
    metadata || {},
    this.methodDescriptorDeleteJobApplication);
  }

}

