/**
 * @fileoverview gRPC-Web generated client stub for job_application_service
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.27.3
// source: job_application.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.job_application_service = require('./job_application_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.job_application_service.JobApplicationServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.job_application_service.JobApplicationServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.job_application_service.CreateJobApplicationRequest,
 *   !proto.job_application_service.CreateJobApplicationResponse>}
 */
const methodDescriptor_JobApplicationService_CreateJobApplication = new grpc.web.MethodDescriptor(
  '/job_application_service.JobApplicationService/CreateJobApplication',
  grpc.web.MethodType.UNARY,
  proto.job_application_service.CreateJobApplicationRequest,
  proto.job_application_service.CreateJobApplicationResponse,
  /**
   * @param {!proto.job_application_service.CreateJobApplicationRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.job_application_service.CreateJobApplicationResponse.deserializeBinary
);


/**
 * @param {!proto.job_application_service.CreateJobApplicationRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.job_application_service.CreateJobApplicationResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.job_application_service.CreateJobApplicationResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.job_application_service.JobApplicationServiceClient.prototype.createJobApplication =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/job_application_service.JobApplicationService/CreateJobApplication',
      request,
      metadata || {},
      methodDescriptor_JobApplicationService_CreateJobApplication,
      callback);
};


/**
 * @param {!proto.job_application_service.CreateJobApplicationRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.job_application_service.CreateJobApplicationResponse>}
 *     Promise that resolves to the response
 */
proto.job_application_service.JobApplicationServicePromiseClient.prototype.createJobApplication =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/job_application_service.JobApplicationService/CreateJobApplication',
      request,
      metadata || {},
      methodDescriptor_JobApplicationService_CreateJobApplication);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.job_application_service.ReadJobApplicationRequest,
 *   !proto.job_application_service.ReadJobApplicationResponse>}
 */
const methodDescriptor_JobApplicationService_ReadJobApplication = new grpc.web.MethodDescriptor(
  '/job_application_service.JobApplicationService/ReadJobApplication',
  grpc.web.MethodType.UNARY,
  proto.job_application_service.ReadJobApplicationRequest,
  proto.job_application_service.ReadJobApplicationResponse,
  /**
   * @param {!proto.job_application_service.ReadJobApplicationRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.job_application_service.ReadJobApplicationResponse.deserializeBinary
);


/**
 * @param {!proto.job_application_service.ReadJobApplicationRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.job_application_service.ReadJobApplicationResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.job_application_service.ReadJobApplicationResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.job_application_service.JobApplicationServiceClient.prototype.readJobApplication =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/job_application_service.JobApplicationService/ReadJobApplication',
      request,
      metadata || {},
      methodDescriptor_JobApplicationService_ReadJobApplication,
      callback);
};


/**
 * @param {!proto.job_application_service.ReadJobApplicationRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.job_application_service.ReadJobApplicationResponse>}
 *     Promise that resolves to the response
 */
proto.job_application_service.JobApplicationServicePromiseClient.prototype.readJobApplication =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/job_application_service.JobApplicationService/ReadJobApplication',
      request,
      metadata || {},
      methodDescriptor_JobApplicationService_ReadJobApplication);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.job_application_service.UpdateJobApplicationRequest,
 *   !proto.job_application_service.UpdateJobApplicationResponse>}
 */
const methodDescriptor_JobApplicationService_UpdateJobApplication = new grpc.web.MethodDescriptor(
  '/job_application_service.JobApplicationService/UpdateJobApplication',
  grpc.web.MethodType.UNARY,
  proto.job_application_service.UpdateJobApplicationRequest,
  proto.job_application_service.UpdateJobApplicationResponse,
  /**
   * @param {!proto.job_application_service.UpdateJobApplicationRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.job_application_service.UpdateJobApplicationResponse.deserializeBinary
);


/**
 * @param {!proto.job_application_service.UpdateJobApplicationRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.job_application_service.UpdateJobApplicationResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.job_application_service.UpdateJobApplicationResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.job_application_service.JobApplicationServiceClient.prototype.updateJobApplication =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/job_application_service.JobApplicationService/UpdateJobApplication',
      request,
      metadata || {},
      methodDescriptor_JobApplicationService_UpdateJobApplication,
      callback);
};


/**
 * @param {!proto.job_application_service.UpdateJobApplicationRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.job_application_service.UpdateJobApplicationResponse>}
 *     Promise that resolves to the response
 */
proto.job_application_service.JobApplicationServicePromiseClient.prototype.updateJobApplication =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/job_application_service.JobApplicationService/UpdateJobApplication',
      request,
      metadata || {},
      methodDescriptor_JobApplicationService_UpdateJobApplication);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.job_application_service.DeleteJobApplicationRequest,
 *   !proto.job_application_service.DeleteJobApplicationResponse>}
 */
const methodDescriptor_JobApplicationService_DeleteJobApplication = new grpc.web.MethodDescriptor(
  '/job_application_service.JobApplicationService/DeleteJobApplication',
  grpc.web.MethodType.UNARY,
  proto.job_application_service.DeleteJobApplicationRequest,
  proto.job_application_service.DeleteJobApplicationResponse,
  /**
   * @param {!proto.job_application_service.DeleteJobApplicationRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.job_application_service.DeleteJobApplicationResponse.deserializeBinary
);


/**
 * @param {!proto.job_application_service.DeleteJobApplicationRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.job_application_service.DeleteJobApplicationResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.job_application_service.DeleteJobApplicationResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.job_application_service.JobApplicationServiceClient.prototype.deleteJobApplication =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/job_application_service.JobApplicationService/DeleteJobApplication',
      request,
      metadata || {},
      methodDescriptor_JobApplicationService_DeleteJobApplication,
      callback);
};


/**
 * @param {!proto.job_application_service.DeleteJobApplicationRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.job_application_service.DeleteJobApplicationResponse>}
 *     Promise that resolves to the response
 */
proto.job_application_service.JobApplicationServicePromiseClient.prototype.deleteJobApplication =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/job_application_service.JobApplicationService/DeleteJobApplication',
      request,
      metadata || {},
      methodDescriptor_JobApplicationService_DeleteJobApplication);
};


module.exports = proto.job_application_service;

