/**
 * @fileoverview gRPC-Web generated client stub for job_posting_service
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.27.3
// source: job_posting.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as job_posting_pb from './job_posting_pb'; // proto import: "job_posting.proto"


export class JobPostingServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreateJobPosting = new grpcWeb.MethodDescriptor(
    '/job_posting_service.JobPostingService/CreateJobPosting',
    grpcWeb.MethodType.UNARY,
    job_posting_pb.CreateJobPostingRequest,
    job_posting_pb.CreateJobPostingResponse,
    (request: job_posting_pb.CreateJobPostingRequest) => {
      return request.serializeBinary();
    },
    job_posting_pb.CreateJobPostingResponse.deserializeBinary
  );

  createJobPosting(
    request: job_posting_pb.CreateJobPostingRequest,
    metadata?: grpcWeb.Metadata | null): Promise<job_posting_pb.CreateJobPostingResponse>;

  createJobPosting(
    request: job_posting_pb.CreateJobPostingRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: job_posting_pb.CreateJobPostingResponse) => void): grpcWeb.ClientReadableStream<job_posting_pb.CreateJobPostingResponse>;

  createJobPosting(
    request: job_posting_pb.CreateJobPostingRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: job_posting_pb.CreateJobPostingResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/job_posting_service.JobPostingService/CreateJobPosting',
        request,
        metadata || {},
        this.methodDescriptorCreateJobPosting,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/job_posting_service.JobPostingService/CreateJobPosting',
    request,
    metadata || {},
    this.methodDescriptorCreateJobPosting);
  }

  methodDescriptorReadJobPosting = new grpcWeb.MethodDescriptor(
    '/job_posting_service.JobPostingService/ReadJobPosting',
    grpcWeb.MethodType.UNARY,
    job_posting_pb.ReadJobPostingRequest,
    job_posting_pb.ReadJobPostingResponse,
    (request: job_posting_pb.ReadJobPostingRequest) => {
      return request.serializeBinary();
    },
    job_posting_pb.ReadJobPostingResponse.deserializeBinary
  );

  readJobPosting(
    request: job_posting_pb.ReadJobPostingRequest,
    metadata?: grpcWeb.Metadata | null): Promise<job_posting_pb.ReadJobPostingResponse>;

  readJobPosting(
    request: job_posting_pb.ReadJobPostingRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: job_posting_pb.ReadJobPostingResponse) => void): grpcWeb.ClientReadableStream<job_posting_pb.ReadJobPostingResponse>;

  readJobPosting(
    request: job_posting_pb.ReadJobPostingRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: job_posting_pb.ReadJobPostingResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/job_posting_service.JobPostingService/ReadJobPosting',
        request,
        metadata || {},
        this.methodDescriptorReadJobPosting,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/job_posting_service.JobPostingService/ReadJobPosting',
    request,
    metadata || {},
    this.methodDescriptorReadJobPosting);
  }

  methodDescriptorUpdateJobPosting = new grpcWeb.MethodDescriptor(
    '/job_posting_service.JobPostingService/UpdateJobPosting',
    grpcWeb.MethodType.UNARY,
    job_posting_pb.UpdateJobPostingRequest,
    job_posting_pb.UpdateJobPostingResponse,
    (request: job_posting_pb.UpdateJobPostingRequest) => {
      return request.serializeBinary();
    },
    job_posting_pb.UpdateJobPostingResponse.deserializeBinary
  );

  updateJobPosting(
    request: job_posting_pb.UpdateJobPostingRequest,
    metadata?: grpcWeb.Metadata | null): Promise<job_posting_pb.UpdateJobPostingResponse>;

  updateJobPosting(
    request: job_posting_pb.UpdateJobPostingRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: job_posting_pb.UpdateJobPostingResponse) => void): grpcWeb.ClientReadableStream<job_posting_pb.UpdateJobPostingResponse>;

  updateJobPosting(
    request: job_posting_pb.UpdateJobPostingRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: job_posting_pb.UpdateJobPostingResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/job_posting_service.JobPostingService/UpdateJobPosting',
        request,
        metadata || {},
        this.methodDescriptorUpdateJobPosting,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/job_posting_service.JobPostingService/UpdateJobPosting',
    request,
    metadata || {},
    this.methodDescriptorUpdateJobPosting);
  }

  methodDescriptorDeleteJobPosting = new grpcWeb.MethodDescriptor(
    '/job_posting_service.JobPostingService/DeleteJobPosting',
    grpcWeb.MethodType.UNARY,
    job_posting_pb.DeleteJobPostingRequest,
    job_posting_pb.DeleteJobPostingResponse,
    (request: job_posting_pb.DeleteJobPostingRequest) => {
      return request.serializeBinary();
    },
    job_posting_pb.DeleteJobPostingResponse.deserializeBinary
  );

  deleteJobPosting(
    request: job_posting_pb.DeleteJobPostingRequest,
    metadata?: grpcWeb.Metadata | null): Promise<job_posting_pb.DeleteJobPostingResponse>;

  deleteJobPosting(
    request: job_posting_pb.DeleteJobPostingRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: job_posting_pb.DeleteJobPostingResponse) => void): grpcWeb.ClientReadableStream<job_posting_pb.DeleteJobPostingResponse>;

  deleteJobPosting(
    request: job_posting_pb.DeleteJobPostingRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: job_posting_pb.DeleteJobPostingResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/job_posting_service.JobPostingService/DeleteJobPosting',
        request,
        metadata || {},
        this.methodDescriptorDeleteJobPosting,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/job_posting_service.JobPostingService/DeleteJobPosting',
    request,
    metadata || {},
    this.methodDescriptorDeleteJobPosting);
  }

}

