// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: job_application.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JobApplicationService_CreateJobApplication_FullMethodName = "/job_application_service.JobApplicationService/CreateJobApplication"
	JobApplicationService_ReadJobApplication_FullMethodName   = "/job_application_service.JobApplicationService/ReadJobApplication"
	JobApplicationService_UpdateJobApplication_FullMethodName = "/job_application_service.JobApplicationService/UpdateJobApplication"
	JobApplicationService_DeleteJobApplication_FullMethodName = "/job_application_service.JobApplicationService/DeleteJobApplication"
)

// JobApplicationServiceClient is the client API for JobApplicationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JobApplicationServiceClient interface {
	CreateJobApplication(ctx context.Context, in *CreateJobApplicationRequest, opts ...grpc.CallOption) (*CreateJobApplicationResponse, error)
	ReadJobApplication(ctx context.Context, in *ReadJobApplicationRequest, opts ...grpc.CallOption) (*ReadJobApplicationResponse, error)
	UpdateJobApplication(ctx context.Context, in *UpdateJobApplicationRequest, opts ...grpc.CallOption) (*UpdateJobApplicationResponse, error)
	DeleteJobApplication(ctx context.Context, in *DeleteJobApplicationRequest, opts ...grpc.CallOption) (*DeleteJobApplicationResponse, error)
}

type jobApplicationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJobApplicationServiceClient(cc grpc.ClientConnInterface) JobApplicationServiceClient {
	return &jobApplicationServiceClient{cc}
}

func (c *jobApplicationServiceClient) CreateJobApplication(ctx context.Context, in *CreateJobApplicationRequest, opts ...grpc.CallOption) (*CreateJobApplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateJobApplicationResponse)
	err := c.cc.Invoke(ctx, JobApplicationService_CreateJobApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobApplicationServiceClient) ReadJobApplication(ctx context.Context, in *ReadJobApplicationRequest, opts ...grpc.CallOption) (*ReadJobApplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadJobApplicationResponse)
	err := c.cc.Invoke(ctx, JobApplicationService_ReadJobApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobApplicationServiceClient) UpdateJobApplication(ctx context.Context, in *UpdateJobApplicationRequest, opts ...grpc.CallOption) (*UpdateJobApplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateJobApplicationResponse)
	err := c.cc.Invoke(ctx, JobApplicationService_UpdateJobApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobApplicationServiceClient) DeleteJobApplication(ctx context.Context, in *DeleteJobApplicationRequest, opts ...grpc.CallOption) (*DeleteJobApplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteJobApplicationResponse)
	err := c.cc.Invoke(ctx, JobApplicationService_DeleteJobApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobApplicationServiceServer is the server API for JobApplicationService service.
// All implementations must embed UnimplementedJobApplicationServiceServer
// for forward compatibility.
type JobApplicationServiceServer interface {
	CreateJobApplication(context.Context, *CreateJobApplicationRequest) (*CreateJobApplicationResponse, error)
	ReadJobApplication(context.Context, *ReadJobApplicationRequest) (*ReadJobApplicationResponse, error)
	UpdateJobApplication(context.Context, *UpdateJobApplicationRequest) (*UpdateJobApplicationResponse, error)
	DeleteJobApplication(context.Context, *DeleteJobApplicationRequest) (*DeleteJobApplicationResponse, error)
	mustEmbedUnimplementedJobApplicationServiceServer()
}

// UnimplementedJobApplicationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobApplicationServiceServer struct{}

func (UnimplementedJobApplicationServiceServer) CreateJobApplication(context.Context, *CreateJobApplicationRequest) (*CreateJobApplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateJobApplication not implemented")
}
func (UnimplementedJobApplicationServiceServer) ReadJobApplication(context.Context, *ReadJobApplicationRequest) (*ReadJobApplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadJobApplication not implemented")
}
func (UnimplementedJobApplicationServiceServer) UpdateJobApplication(context.Context, *UpdateJobApplicationRequest) (*UpdateJobApplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateJobApplication not implemented")
}
func (UnimplementedJobApplicationServiceServer) DeleteJobApplication(context.Context, *DeleteJobApplicationRequest) (*DeleteJobApplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteJobApplication not implemented")
}
func (UnimplementedJobApplicationServiceServer) mustEmbedUnimplementedJobApplicationServiceServer() {}
func (UnimplementedJobApplicationServiceServer) testEmbeddedByValue()                               {}

// UnsafeJobApplicationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobApplicationServiceServer will
// result in compilation errors.
type UnsafeJobApplicationServiceServer interface {
	mustEmbedUnimplementedJobApplicationServiceServer()
}

func RegisterJobApplicationServiceServer(s grpc.ServiceRegistrar, srv JobApplicationServiceServer) {
	// If the following call pancis, it indicates UnimplementedJobApplicationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JobApplicationService_ServiceDesc, srv)
}

func _JobApplicationService_CreateJobApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobApplicationServiceServer).CreateJobApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobApplicationService_CreateJobApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobApplicationServiceServer).CreateJobApplication(ctx, req.(*CreateJobApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobApplicationService_ReadJobApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadJobApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobApplicationServiceServer).ReadJobApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobApplicationService_ReadJobApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobApplicationServiceServer).ReadJobApplication(ctx, req.(*ReadJobApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobApplicationService_UpdateJobApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateJobApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobApplicationServiceServer).UpdateJobApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobApplicationService_UpdateJobApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobApplicationServiceServer).UpdateJobApplication(ctx, req.(*UpdateJobApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobApplicationService_DeleteJobApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteJobApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobApplicationServiceServer).DeleteJobApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobApplicationService_DeleteJobApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobApplicationServiceServer).DeleteJobApplication(ctx, req.(*DeleteJobApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JobApplicationService_ServiceDesc is the grpc.ServiceDesc for JobApplicationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobApplicationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "job_application_service.JobApplicationService",
	HandlerType: (*JobApplicationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateJobApplication",
			Handler:    _JobApplicationService_CreateJobApplication_Handler,
		},
		{
			MethodName: "ReadJobApplication",
			Handler:    _JobApplicationService_ReadJobApplication_Handler,
		},
		{
			MethodName: "UpdateJobApplication",
			Handler:    _JobApplicationService_UpdateJobApplication_Handler,
		},
		{
			MethodName: "DeleteJobApplication",
			Handler:    _JobApplicationService_DeleteJobApplication_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "job_application.proto",
}
