// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: job_application.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateJobApplicationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateJobApplicationRequest) Reset() {
	*x = CreateJobApplicationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_application_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateJobApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobApplicationRequest) ProtoMessage() {}

func (x *CreateJobApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_application_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobApplicationRequest.ProtoReflect.Descriptor instead.
func (*CreateJobApplicationRequest) Descriptor() ([]byte, []int) {
	return file_job_application_proto_rawDescGZIP(), []int{0}
}

type CreateJobApplicationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateJobApplicationResponse) Reset() {
	*x = CreateJobApplicationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_application_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateJobApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobApplicationResponse) ProtoMessage() {}

func (x *CreateJobApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_application_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobApplicationResponse.ProtoReflect.Descriptor instead.
func (*CreateJobApplicationResponse) Descriptor() ([]byte, []int) {
	return file_job_application_proto_rawDescGZIP(), []int{1}
}

type ReadJobApplicationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadJobApplicationRequest) Reset() {
	*x = ReadJobApplicationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_application_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadJobApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadJobApplicationRequest) ProtoMessage() {}

func (x *ReadJobApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_application_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadJobApplicationRequest.ProtoReflect.Descriptor instead.
func (*ReadJobApplicationRequest) Descriptor() ([]byte, []int) {
	return file_job_application_proto_rawDescGZIP(), []int{2}
}

type ReadJobApplicationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadJobApplicationResponse) Reset() {
	*x = ReadJobApplicationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_application_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadJobApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadJobApplicationResponse) ProtoMessage() {}

func (x *ReadJobApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_application_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadJobApplicationResponse.ProtoReflect.Descriptor instead.
func (*ReadJobApplicationResponse) Descriptor() ([]byte, []int) {
	return file_job_application_proto_rawDescGZIP(), []int{3}
}

type UpdateJobApplicationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateJobApplicationRequest) Reset() {
	*x = UpdateJobApplicationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_application_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateJobApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJobApplicationRequest) ProtoMessage() {}

func (x *UpdateJobApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_application_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJobApplicationRequest.ProtoReflect.Descriptor instead.
func (*UpdateJobApplicationRequest) Descriptor() ([]byte, []int) {
	return file_job_application_proto_rawDescGZIP(), []int{4}
}

type UpdateJobApplicationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateJobApplicationResponse) Reset() {
	*x = UpdateJobApplicationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_application_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateJobApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJobApplicationResponse) ProtoMessage() {}

func (x *UpdateJobApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_application_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJobApplicationResponse.ProtoReflect.Descriptor instead.
func (*UpdateJobApplicationResponse) Descriptor() ([]byte, []int) {
	return file_job_application_proto_rawDescGZIP(), []int{5}
}

type DeleteJobApplicationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteJobApplicationRequest) Reset() {
	*x = DeleteJobApplicationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_application_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteJobApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteJobApplicationRequest) ProtoMessage() {}

func (x *DeleteJobApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_application_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteJobApplicationRequest.ProtoReflect.Descriptor instead.
func (*DeleteJobApplicationRequest) Descriptor() ([]byte, []int) {
	return file_job_application_proto_rawDescGZIP(), []int{6}
}

type DeleteJobApplicationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteJobApplicationResponse) Reset() {
	*x = DeleteJobApplicationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_application_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteJobApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteJobApplicationResponse) ProtoMessage() {}

func (x *DeleteJobApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_application_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteJobApplicationResponse.ProtoReflect.Descriptor instead.
func (*DeleteJobApplicationResponse) Descriptor() ([]byte, []int) {
	return file_job_application_proto_rawDescGZIP(), []int{7}
}

var File_job_application_proto protoreflect.FileDescriptor

var file_job_application_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6a, 0x6f, 0x62, 0x5f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x6a, 0x6f, 0x62, 0x5f, 0x61, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x22, 0x1d, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x41, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x1e, 0x0a, 0x1c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x41, 0x70, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x1b, 0x0a, 0x19, 0x52, 0x65, 0x61, 0x64, 0x4a, 0x6f, 0x62, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1c, 0x0a, 0x1a,
	0x52, 0x65, 0x61, 0x64, 0x4a, 0x6f, 0x62, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1d, 0x0a, 0x1b, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1e, 0x0a, 0x1c, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1d, 0x0a, 0x1b, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1e, 0x0a, 0x1c, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x4a, 0x6f, 0x62, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xb0, 0x04, 0x0a, 0x15, 0x4a, 0x6f, 0x62,
	0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x85, 0x01, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4a, 0x6f, 0x62,
	0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x34, 0x2e, 0x6a, 0x6f,
	0x62, 0x5f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x41,
	0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x35, 0x2e, 0x6a, 0x6f, 0x62, 0x5f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4a, 0x6f, 0x62, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x7f, 0x0a, 0x12, 0x52, 0x65,
	0x61, 0x64, 0x4a, 0x6f, 0x62, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x32, 0x2e, 0x6a, 0x6f, 0x62, 0x5f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x4a,
	0x6f, 0x62, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x33, 0x2e, 0x6a, 0x6f, 0x62, 0x5f, 0x61, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52,
	0x65, 0x61, 0x64, 0x4a, 0x6f, 0x62, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x85, 0x01, 0x0a, 0x14,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x34, 0x2e, 0x6a, 0x6f, 0x62, 0x5f, 0x61, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x35, 0x2e, 0x6a, 0x6f, 0x62,
	0x5f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x41, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x85, 0x01, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4a, 0x6f,
	0x62, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x34, 0x2e, 0x6a,
	0x6f, 0x62, 0x5f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4a, 0x6f, 0x62,
	0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x35, 0x2e, 0x6a, 0x6f, 0x62, 0x5f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_job_application_proto_rawDescOnce sync.Once
	file_job_application_proto_rawDescData = file_job_application_proto_rawDesc
)

func file_job_application_proto_rawDescGZIP() []byte {
	file_job_application_proto_rawDescOnce.Do(func() {
		file_job_application_proto_rawDescData = protoimpl.X.CompressGZIP(file_job_application_proto_rawDescData)
	})
	return file_job_application_proto_rawDescData
}

var file_job_application_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_job_application_proto_goTypes = []any{
	(*CreateJobApplicationRequest)(nil),  // 0: job_application_service.CreateJobApplicationRequest
	(*CreateJobApplicationResponse)(nil), // 1: job_application_service.CreateJobApplicationResponse
	(*ReadJobApplicationRequest)(nil),    // 2: job_application_service.ReadJobApplicationRequest
	(*ReadJobApplicationResponse)(nil),   // 3: job_application_service.ReadJobApplicationResponse
	(*UpdateJobApplicationRequest)(nil),  // 4: job_application_service.UpdateJobApplicationRequest
	(*UpdateJobApplicationResponse)(nil), // 5: job_application_service.UpdateJobApplicationResponse
	(*DeleteJobApplicationRequest)(nil),  // 6: job_application_service.DeleteJobApplicationRequest
	(*DeleteJobApplicationResponse)(nil), // 7: job_application_service.DeleteJobApplicationResponse
}
var file_job_application_proto_depIdxs = []int32{
	0, // 0: job_application_service.JobApplicationService.CreateJobApplication:input_type -> job_application_service.CreateJobApplicationRequest
	2, // 1: job_application_service.JobApplicationService.ReadJobApplication:input_type -> job_application_service.ReadJobApplicationRequest
	4, // 2: job_application_service.JobApplicationService.UpdateJobApplication:input_type -> job_application_service.UpdateJobApplicationRequest
	6, // 3: job_application_service.JobApplicationService.DeleteJobApplication:input_type -> job_application_service.DeleteJobApplicationRequest
	1, // 4: job_application_service.JobApplicationService.CreateJobApplication:output_type -> job_application_service.CreateJobApplicationResponse
	3, // 5: job_application_service.JobApplicationService.ReadJobApplication:output_type -> job_application_service.ReadJobApplicationResponse
	5, // 6: job_application_service.JobApplicationService.UpdateJobApplication:output_type -> job_application_service.UpdateJobApplicationResponse
	7, // 7: job_application_service.JobApplicationService.DeleteJobApplication:output_type -> job_application_service.DeleteJobApplicationResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_job_application_proto_init() }
func file_job_application_proto_init() {
	if File_job_application_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_job_application_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreateJobApplicationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_job_application_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateJobApplicationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_job_application_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ReadJobApplicationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_job_application_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ReadJobApplicationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_job_application_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateJobApplicationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_job_application_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateJobApplicationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_job_application_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteJobApplicationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_job_application_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteJobApplicationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_job_application_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_job_application_proto_goTypes,
		DependencyIndexes: file_job_application_proto_depIdxs,
		MessageInfos:      file_job_application_proto_msgTypes,
	}.Build()
	File_job_application_proto = out.File
	file_job_application_proto_rawDesc = nil
	file_job_application_proto_goTypes = nil
	file_job_application_proto_depIdxs = nil
}
