// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: job_interview.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobInterviewRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *JobInterviewRequest) Reset() {
	*x = JobInterviewRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_interview_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobInterviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobInterviewRequest) ProtoMessage() {}

func (x *JobInterviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_interview_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobInterviewRequest.ProtoReflect.Descriptor instead.
func (*JobInterviewRequest) Descriptor() ([]byte, []int) {
	return file_job_interview_proto_rawDescGZIP(), []int{0}
}

type JobInterviewResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *JobInterviewResponse) Reset() {
	*x = JobInterviewResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_interview_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobInterviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobInterviewResponse) ProtoMessage() {}

func (x *JobInterviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_interview_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobInterviewResponse.ProtoReflect.Descriptor instead.
func (*JobInterviewResponse) Descriptor() ([]byte, []int) {
	return file_job_interview_proto_rawDescGZIP(), []int{1}
}

var File_job_interview_proto protoreflect.FileDescriptor

var file_job_interview_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x76, 0x69, 0x65, 0x77, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x15, 0x0a, 0x13,
	0x4a, 0x6f, 0x62, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x4a, 0x6f, 0x62, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76,
	0x69, 0x65, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x81, 0x02, 0x0a, 0x13,
	0x4a, 0x6f, 0x62, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x6e, 0x0a, 0x11, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x43, 0x6f, 0x6e, 0x76,
	0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x2e, 0x6a, 0x6f, 0x62, 0x5f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x4a, 0x6f, 0x62, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x76, 0x69, 0x65, 0x77, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4a, 0x6f, 0x62,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x7a, 0x0a, 0x19, 0x42, 0x69, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x2a, 0x2e, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4a, 0x6f, 0x62, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x76, 0x69, 0x65, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x6a,
	0x6f, 0x62, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x4a, 0x6f, 0x62, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65,
	0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42,
	0x08, 0x5a, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_job_interview_proto_rawDescOnce sync.Once
	file_job_interview_proto_rawDescData = file_job_interview_proto_rawDesc
)

func file_job_interview_proto_rawDescGZIP() []byte {
	file_job_interview_proto_rawDescOnce.Do(func() {
		file_job_interview_proto_rawDescData = protoimpl.X.CompressGZIP(file_job_interview_proto_rawDescData)
	})
	return file_job_interview_proto_rawDescData
}

var file_job_interview_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_job_interview_proto_goTypes = []any{
	(*JobInterviewRequest)(nil),  // 0: job_interview_service.JobInterviewRequest
	(*JobInterviewResponse)(nil), // 1: job_interview_service.JobInterviewResponse
}
var file_job_interview_proto_depIdxs = []int32{
	0, // 0: job_interview_service.JobInterviewService.UnaryConversation:input_type -> job_interview_service.JobInterviewRequest
	0, // 1: job_interview_service.JobInterviewService.BidirectionalConversation:input_type -> job_interview_service.JobInterviewRequest
	1, // 2: job_interview_service.JobInterviewService.UnaryConversation:output_type -> job_interview_service.JobInterviewResponse
	1, // 3: job_interview_service.JobInterviewService.BidirectionalConversation:output_type -> job_interview_service.JobInterviewResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_job_interview_proto_init() }
func file_job_interview_proto_init() {
	if File_job_interview_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_job_interview_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*JobInterviewRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_job_interview_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*JobInterviewResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_job_interview_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_job_interview_proto_goTypes,
		DependencyIndexes: file_job_interview_proto_depIdxs,
		MessageInfos:      file_job_interview_proto_msgTypes,
	}.Build()
	File_job_interview_proto = out.File
	file_job_interview_proto_rawDesc = nil
	file_job_interview_proto_goTypes = nil
	file_job_interview_proto_depIdxs = nil
}
